### ISSUE TITLE
Can it be case insensitive?

### ISSUE THREAD

**Issue by funnybunnyQAQ** [yiminzme/Multi-Highlight#15]
Hi there,

This is Funnybunny from China. I am using the Multi Highlight Options and found it really helpful. Somehow, I want a case-sensitive feature added if you are available, that could be brilliant and top all other multi highlight tools.

Thanks for your checking and consideration.

**Comment by yiminzme** [comment]
Ok, I will consider adding case sensitive feature in the future version.

**Comment by TroyDanielFZ** [comment]
Feature added in last merged commit.

**Comment by yiminzme** [comment]
Thanks~ @TroyDanielFZ
