### ISSUE TITLE
已经添加的字词，经常会被清空掉，希望改进。谢谢

### ISSUE THREAD

**Issue by zhangzc2012s** [yiminzme/Multi-Highlight#16]
已经添加的字词，经常会被清空掉，希望改进。谢谢

**Comment by yiminzme** [comment]
Hi, please enable the "always highlight" feature to save your word list.


![20211106capture](https://user-images.githubusercontent.com/11984137/140605025-be69bf46-cab0-4e5d-b18a-2bd04b6c9f60.png)

**Comment by zhangzc2012s** [comment]
> Hi, please enable the "always highlight" feature to save your word list.
> 
> ![20211106capture](https://user-images.githubusercontent.com/11984137/140605025-be69bf46-cab0-4e5d-b18a-2bd04b6c9f60.png)

这些选项，我都已经选择了，还是会

**Comment by Gez0377** [comment]
我也遇到这个问题

**Comment by TroyDanielFZ** [comment]
试试最新合并的内容呢？看看还会不会被清空？

**Comment by Gez0377** [comment]
> 试试最新合并的内容呢？看看还会不会被清空？

重新安装了下, 暂时还没有重新出现这个情况.
