### ISSUE TITLE
Latest Update Broke Extension in Chrome

### ISSUE THREAD

**Issue by Sonnebahn** [yiminzme/Multi-Highlight#20]
Thank You for your hard work on this Extension for Chrome. I use this almost daily.

The Latest updates that hit Chrome about Jan 5, and was committed here Jan 2 created a reset loop.
No matter which checkboxes are selected or unselected they will revert to the last setting (default perhaps) when the window is closed. Further, the keyword list will also clear. And even with auto highlight option checked, the keywords do not highlight as you type them into the box.
In effect, this is like it is constantly triggering a reset event whenever the window is closed, and keywords are not even being entered into the search array.

**Comment by Sonnebahn** [comment]
I am not certain why, but I have gotten it to work. Here are the things I did that eventually caused it to work.

1. Uninstalled and reinstalled : no noticeable change

2. Uninstalled and downloaded zip file of extension to locally adjust code and load in developer mode. 
- reverted changes to lib.js
- installed local version
- :no noticeable change 

3. uninstalled local version
- reapplied changes to lib.js
- reverted changes to options.html
- installed local version
: no noticeable change
- changed delimiter in options page
: all functions working
- reapplied changes to options.html
: all functions still working

4. uninstalled local version
- reinstalled official version
: no functions working
- reload page
: all functions working

The most likely scenario I can determine is the combination of uninstalling, reinstalling and a manual reload of the page straightened out whatever was breaking it. However, I cannot discount the change of the delimiter in the options page which had an immediate result without a reload of the page. And knowing that when the break first happened the extension asked for a reload like normal, but that had no effect in and of itself.

**Comment by Sonnebahn** [comment]
Noticed one last thing:
the keyword listing is now saved per tab. that is to say on two separate tabs I can enter two different sets of keywords. Not sure if this was a feature change I missed a while back, or if this is a new behavior. I used to be able to carry changes across multiple tabs (i.e. enter a change in tab 1 and have the change present in tab 2)

**Comment by yiminzme** [comment]
@Sonnebahn 

> I am not certain why, but I have gotten it to work

Nice that you got it to work.

> The most likely scenario I can determine is the combination of uninstalling, reinstalling and a manual reload of the page straightened out whatever was breaking it. However, I cannot discount the change of the delimiter in the options page which had an immediate result without a reload of the page. And knowing that when the break first happened the extension asked for a reload like normal, but that had no effect in and of itself.

Yeah, the updating process of chrome/edge extension often confuses me as well. The process sometimes doesn't respond in time. By the way, do you think "delimiter" is a good word to use? Seems like it is not a commonly used word, maybe "separator" is a better word? any suggestion?

> the keyword listing is now saved per tab. that is to say on two separate tabs I can enter two different sets of keywords. Not sure if this was a feature change I missed a while back, or if this is a new behavior. I used to be able to carry changes across multiple tabs (i.e. enter a change in tab 1 and have the change present in tab 2)

This feature exists before the latest update. Use the `Keep existing words in new tab` checkbox to toggle this feature, as its name suggests. Notice that this setting only affects tabs you open afterward.

**Comment by Sonnebahn** [comment]
@yiminzme 

>  By the way, do you think "delimiter" is a good word to use? Seems like it is not a commonly used word, maybe "separator" is a better word? any suggestion?
From a power user perspective 'delimiter' makes sense. I am used to dealing with data files delimited by commas, semicolons, spaces, etc. Though you may want to consider adding 'separate' to the tooltip description.


> This feature exists before the latest update. Use the `Keep existing words in new tab` checkbox to toggle this feature, as its name suggests. Notice that this setting only affects tabs you open afterward.
makes sense, I rarely close the windows I am working in with this extension.
