### ISSUE TITLE
Highlighting all words, even if substring is placed before a longer string

### ISSUE THREAD

**Issue by yiminzme** [yiminzme/Multi-Highlight#21]
If a substring is placed before a longer string, the longer string won't be highlighted now.
For example, in the [example page](https://www.google.com/search?q=asdfasdf&oq=asdfasdf&aqs=edge.0.69i59j0i12i512l3j0i512l2.460j0j4&sourceid=chrome&ie=UTF-8), if we put "asd,asdf" in the textbox, word "asdf" won't be highlighted. But it will work if we put "asdf,asd" in the textbox instead.

To fix this bug, 
(1) sort the word list by length
(2) then highlight words one by one from longest to shortest.

**Comment by bendeutz** [comment]
Hey, i think i found a way to fix this. Although im not new to git, im really new to contribute to other projects, so im not really sure what is the best way to send this fix to you to check it? 

I already forked the project and pushed the fix (hopefully)!

Let me know if i can do anything else to make your life easier.

Regards,
ben

**Comment by bendeutz** [comment]
Hey yiminzme,

i tried to work on this problem but i run into a few others. Maybe you can give me your thoughts on this: 

1. I think something is not right with the `hl_clear`-method. If you put in "asdf, asd" and you clear the input completely (mark all of it and remove it at once) then you remove the actual html on the page itself.
2. I think something else is going on in the `hl_search`-method. In the else-part sometimes i get double dashes in the cls-variable. Im not really sure why tho...

Im not sure if you can do something with the stuff i wrote here, hopefully you can :)

I would love to help, but im not really sure where to begin to fix this.

If im wrong anywhere, dont hesitate to correct me :-)

Regards, 
Ben

**Comment by yiminzme** [comment]
Hi @bendeutz~
Thanks for helping out.

> im not really sure where to begin to fix this  

Let's start with the `hl_clear` method.

> I think something is not right with the hl_clear-method. If you put in "asdf, asd" and you clear the input completely (mark all of it and remove it at once) then you remove the actual html on the page itself

Yeah, it is definitely a bug. `hl_clear` is supposed to be able to do things I mentioned above. I think it is no longer the case now. As for why, I think it is because `hl_clear`'s parameter `removedKws` is no longer passing **sorted list of words**. Maybe you can (1) figure out who called `hl_clear` (2) whether all calls of `hl_clear` have input a **sorted list of words**. 
Also, you can add additional sanity check in the `hl_clear` method, i.e. in the `hl_clear` itself, also make sure that words in `removedKws` are removed on the right order (remove words with longest length first, shortest length last).

> I think something else is going on in the hl_search-method. In the else-part sometimes i get double dashes in the cls-variable. Im not really sure why tho...

Clearly a bug. Probably its cause is related to `hl_clear` (e.g. because `hl_clear` removed word in the wrong order, some highlighted text are accidentally removed; then only part of the class name is left; then the resulting two dashes you see were actually from two different highlighted words' classes ...)

Best,
yiminzme

**Comment by bendeutz** [comment]
Hi @yiminzme,

thanks for the fast answer. I think your kind of right with the order in the `hl_clear`. But it needs to be from shortest-length first to longest-length last if im not wrong). Adding these lines at the top of `hl_clear` fixed the bug where html-Elements were removed from the page:

```
 removedKws.sort(function (a, b) {
    return a.length - b.length;
  })
``` 

The bug is still there, if you force the program to use the `hl_clearall`-method tho... maybe there is something not working with the `unhighlight`-method? But maybe we dont need to fix this, since the `clearall`-method doesnt seem to be used normally?

I will continue to look into the problem with the substrings :-)

Regards,
ben

**Comment by bendeutz** [comment]
If i add "asd, asdf" at once in the box, then its working, if i sort the `addedKws` in the right way. But if i type it in, then the `hl_search`-Method is handling the both words seperately. 

If you have a recommendation where i should start with the fix, let me know 😃

**Comment by yiminzme** [comment]
Thanks, @bendeutz ~

> The bug is still there, if you force the program to use the hl_clearall-method tho... maybe there is something not working with the unhighlight-method? But maybe we dont need to fix this, since the clearall-method doesnt seem to be used normally?

Maybe you can push your changes to your repository, I will use it to check the causes by loading it to browser.

> But it needs to be from shortest-length first to longest-length last if im not wrong). 

Nice catch, you are probably right~

> If i add "asd, asdf" at once in the box, then its working, if i sort the addedKws in the right way. But if i type it in, then the hl_search-Method is handling the both words separately.

Then the `handle_highlightWords_change` in `lib.js` probably doesn't work properly.
`handle_highlightWords_change` decides which words to add (highlight) and remove (unhighlight). Specifically, `handle_highlightWords_change`'s `addedKws` and `removedKws` should contain words to add (highlight) and remove (unhighlight), after user changed anything (e.g. textbox input, settings).
For this bug, maybe we can use this 'rule' in `handle_highlightWords_change`:
```
temporaryKws = []
For each new word A added by user (`inputKws`):
  For each word B in the previous user input (`savedKws`):
    if B is substring of A:
      add A into temporaryKws
...
When we unhighlight removed words and highlight new words using hl_clear and hl_search [[here](https://github.com/bendeutz/Multi-Highlight/blob/d974cd702241f14dd5a17e75608e98321d1a8fec/src/lib.js#L149)], we also unhighlight and re-highlight `temporaryKws` (substrings of new words from previous user input).
```
Note that the order of `hl_clear` and `hl_search` is important, we should unhighlight before highlighting~

**Comment by bendeutz** [comment]
Hey @yiminzme

i pushed everything. I also added a bad (performance wise) functionality to fix the original problem, but im pretty sure this is not final.

You can reproduce the bug by adding "asd,asdf" (normal typing) and then delete the f. Sometimes i have problems with DOM-Manipulation so im not really sure if the `highlight`-method in `jquery.highlight` is correct, but since we are replacing child-Nodes there, im pretty sure it has something to do with this problem.

**Comment by bendeutz** [comment]
The bug is even worse, when you put "as,asd,asdf" inside of the box... thats gonna be fun 😃

**Comment by yiminzme** [comment]
I found two bugs.
(1) As discussed in the past 4 comments, when we remove a word X, other existing words that are substring of X should be removed and re-add (in proper order).
(2) In `hl_clear` and `hl_search`, we should eliminate duplicate words in `removedKws` and `addedKws` (e.g. by converting to set then back to list). Note that we need to handle it differently depending on `settings.isCasesensitive`.

**Comment by bendeutz** [comment]
You think we can leave `hightlight` in `jquery.highlight` as it is? I tried to play a bit with this method, but unsuccessful 😞

**Comment by yiminzme** [comment]
@bendeutz 
Yeah, `jquery.highlight` is core code. Let's leave it as is.

**Comment by bendeutz** [comment]
I will try to solve this another day. Right now it seems like if we unhighlight `adsf` i can't prevent that the node itself is deleted. Hopefully some sleep will help 😴

**Comment by yiminzme** [comment]
@bendeutz Thanks a lot for your help! 💪🏼

**Comment by bendeutz** [comment]
Thanks :), i hope we get to the ground of this!

One last thing for today: On master-branch, i can recreate the bug aswell:

1. type `asdf,asd` --> highlighting works correctly as stated by you
2. delete the `f`

Maybe you know this already, it wasn't clear to me 😖

**Comment by TroyDanielFZ** [comment]
> I will try to solve this another day. Right now it seems like if we unhighlight `adsf` i can't prevent that the node itself is deleted. Hopefully some sleep will help 😴

Hi guys, I skim the discussion. 
I met the problem that `hl_clear` removes the html content previously. After lots of debugging, I finally found that, this is due to the reason, a `span` created by `jQuery.highlight` is `unhighlight` twice. Hope it helps.


> (2) then highlight words one by one from longest to shortest.



> (2) In `hl_clear` and `hl_search`, we should eliminate duplicate words in `removedKws` and `addedKws` (e.g. by converting to set then back to list). Note that we need to handle it differently depending on `settings.isCasesensitive`. @TroyDanielFZ Since you created `settings.isCasesensitive`, could you fix this part?

The above two are highly correlated to this [discussion](https://github.com/yiminzme/Multi-Highlight/pull/19#issuecomment-1007068571).

I have a idea now. `latest_keywords` (and those similar) take the following structure.
```js
[{kwGrp: kwGroup1, kwStr: kwStr1},
{kwGrp: kwGroup2, kwStr: kwStr2},
{kwGrp: kwGroup3, kwStr: kwStr3},
...];
```
Then, `highlight`, `sort` and others (context menu handler) should be easy to handle.

**Comment by bendeutz** [comment]
>```
>[{kwGrp: kwGroup1, kwStr: kwStr1},
>{kwGrp: kwGroup2, kwStr: kwStr2},
>{kwGrp: kwGroup3, kwStr: kwStr3},
>...];
>```

To clarify: These groups are then substring-groups? This seems like a good idea! I will let you know, if i achieve anything and if this helps! Thanks for the hint!

**Comment by TroyDanielFZ** [comment]
> These groups are then substring-groups?

I cannot figure out what "substring-groups" mean.

In my opinion, the `kwGrp` is the color index, e.g. 0-19 according to the current `highlight.css` settings. `kwStr`s with the same `kwGrp` are then highlighted with the same color.
Example:
`{kwGrp: 0, kwStr: "example"}` indicates highlighting `example` with `.chrome-extension-FindManyStrings-style-1`.

Do I make myself clear?

**Comment by bendeutz** [comment]
> I cannot figure out what "substring-groups" mean.
I meant different words like "hello", "ello" and so on, but i think i was too stuck on this substring problem. 

> Do I make myself clear?
I think so. I will try to figure it out with your help! 👍

**Comment by bendeutz** [comment]
I agree that your solution is better since we dont have to worry about order of elements with different colors, but im not sure how/if it helps with the problem that html-content gets deleted, when an element is multi-highlighted. Maybe i'm missing something?

**Comment by TroyDanielFZ** [comment]
> im not sure how/if it helps with the problem that html-content gets deleted

Just sort and remove duplicates before highlight. No double highlighting, and no double unhighlighting, if this works as I'm thinking.

**Comment by bendeutz** [comment]
I think you are right. I tried to implement it without changing the structure of `latest_keywords` and others. You can see it here: 

https://github.com/bendeutz/Multi-Highlight/commit/1891d7916d82064e0e61ff4f53b6a3cd44cddd3b

This is **not** good performance wise and its still buggy style-wise. Im not sure if i am able to implement it like you want to, but if i can help in any way let me know.

I want to suggest some kind of global counter or something for the decision which color we use for the next highlighting. Your datastructur is probably good for that, aswell.

**Comment by yiminzme** [comment]
The latest submits should resolve all **bugs**.
Please open a new issue if more bugs are found.
