### ISSUE TITLE
HTML-Elements get removed

### ISSUE THREAD

**Issue by bendeutz** [yiminzme/Multi-Highlight#25]
Hey guys, maybe i'm doing something wrong, but this bug is still there on my end.

Steps to reproduce: 

1. Type "asdf,asd" in the search field.
2. Delete the "f".

Correct me, if im wrong :-)

**Comment by yiminzme** [comment]
Hi @bendeutz, please use the latest version from github. this bug should be resolved. 
The version on chrome store should also have this bug resolved.

**Comment by bendeutz** [comment]
I tried both. Are you saying the bug is not happening at your end?

**Comment by yiminzme** [comment]
Yeah, the bug is not happening at my end.

**Comment by bendeutz** [comment]
Im not sure what im doing wrong then. I tried to clone the rep from this source again. Same issue. Do you have another suggestion?  😵‍💫

**Comment by yiminzme** [comment]
@bendeutz Is your extension version 2.7.3 (latest version)? If it is, then probably we encounter a bug somewhere.

**Comment by yiminzme** [comment]
Bugs and features mentioned should be addressed after 848dacc
