### ISSUE TITLE
Highlighting must be forced into a refresh of the search

### ISSUE THREAD

**Issue by Sonnebahn** [yiminzme/Multi-Highlight#26]
I regularly use this extension looking at successive documents on a search site like google patents. After finishing with one document, I search for another document and re-activate the highlight extension. No highlighting occurs until I change the delimiter and revert it back to the proper delimiter.
To repeat:

1. load Google patents.
2. search for document (ex. US6251349B1)
3. open Highlight extension
4. Place settings to include Instant Search, Keep existing words, Auto-highlight, and Only change color on newline
5. enter at least two lines of text (ex. hydrogen hydride | metal alloy) 
6. set delimiter to ' ' (space)
7. search next document (ex. US7118611B2)
8. open Highlight extension
9. Note: no highlighting
10.  change delimiter to ',' (comma)
11. change delimiter back to ' ' (space)
12. Note: highlighting works

**Comment by yiminzme** [comment]
The latest version in the dev branch should fix the problem you mention in Google patents.
I added a listener to fire the highlighting when the tab title or URL is changed.

Please try it out. If no further bug is found, I will upload it to chrome store.💐

**Comment by Sonnebahn** [comment]
That has corrected the issue when Auto-highlight is checked. When unchecked, it still will only highlight after a delimiter reset.

**Comment by yiminzme** [comment]
> That has corrected the issue when Auto-highlight is checked. When unchecked, it still will only highlight after a delimiter reset.

Isn't this the intended behavior? Auto-highlight automatically highlights previously used words when new tabs / page-reload takes place.
By the way, to manually reload the highlighting, besides "delimiter reset", you can "reload the page" (F5), or "ctrl+a, ctrl+x, ctrl+v" to re-paste the words in the popup textbox.

Also, things I think we should add
(1) when the "auto-highlight" is clicked, we should also re-highlight on the current page
(2) when the multi highlight extension icon is clicked, we should re-highlight on the current page.

**Comment by Sonnebahn** [comment]
When Auto-highlight is unchecked, I believe the intended behavior is that clicking on the icon (bringing up the UI window) should activate the search under the present parameters. The description is kind of vague. Ahh, I see this is covered by (2). I also agree with (1); it really should be a blanket that when something in the interface changes the current page should be re-highlighted, but perhaps some changes would not be needed.

**Comment by yiminzme** [comment]
> it really should be a blanket that when something in the interface changes the current page should be re-highlighted, but perhaps some changes would not be needed.

Yeah, though we should consider the scalability/efficiency. Frequently/periodically re-highlighting things might prevent users from maintaining a long word list, or cause severe lag on pages with lots of text.

**Comment by TroyDanielFZ** [comment]
> (2) when the multi highlight extension icon is clicked, we should re-highlight on the current page.

I'm against for this feature. When there are a lot of words, this action can be really time-comsuming. 

In my opinion, when the user bring the option window (e.g. click the icon), (s)he wants to add/remove keywords, change the option. The hightlighted words won't change since last time the option window was closed, so re-highlighting shouldn't make sense.



> (1) when the "auto-highlight" is clicked, we should also re-highlight on the current page

When should the re-highlighting take place should be carefully considered. Two more features should help deal with these problem.

1. A button to toggle highlighting.
2. A button to force refresh highlighting.

**Comment by yiminzme** [comment]
> > (1) when the "auto-highlight" is clicked, we should also re-highlight on the current page
>
> When should the re-highlighting take place should be carefully considered. Two more features should help deal with these problem.
>
> 1. A button to toggle highlighting.
> 2. A button to force refresh highlighting.

Agree.

> > (2) when the multi highlight extension icon is clicked, we should re-highlight on the current page.
>
> I'm against for this feature. 

Agree. How about we re-highlight if the current tab is a newly loaded page and when the auto-highlight mode is disabled. In this case, if we don't re-highlight when user clicked, the user has to re-highlight manually (e.g., re-type all words). Btw, this feature is implemented in b87d9b3cba3fcfb5cd04821d115c2bf48caf7cce.

**Comment by yiminzme** [comment]
Bugs and features mentioned should be addressed after 848daccad449dfdcdd279762ee7a9a10631ab016
