### ISSUE TITLE
[New features] Right click to remove highlighted word, etc

### ISSUE THREAD

**Issue by aminjabari** [yiminzme/Multi-Highlight#3]
Hi
I like this add-on. I use this add-on for learning English 5000 most frequent words.
I add about 500 words every time and your add-on highlights them in the texts. It helps a lot in learning English.
When I consider a word as learned, I want to remove it from highlight entries. I do this manually. I have to find this word in the add-on entries box. sometimes it takes time to find and remove the word.
It would be great that I can remove these words by right clicking on the highlighted word and asking for removal. I want to remove every word that I don't want to be highlighted anymore.

**Is it possible that you add this feature?**

Maybe by adding this feature, the target user of your extension expands or explodes to whom they want to learn English or any other languages.

Thanks in advance

**Comment by vinc96** [comment]
Hi, aminjabari,
Glad to know that this extension helps to learn languages.
The feature you suggested sounds useful. I will consider its feasibility and try to implement it if possible when I get time. Though I am pretty busy recently, it might take weeks to finish this feature. Sorry about the slowness and hope you can find a workaround for removing specific words in the meanwhile.

**Comment by aminjabari** [comment]
Great.
I will be waiting with excitement to use this feature.

Good Luck

**Comment by vinc96** [comment]
Hi aminjabari,
The new feature is available on Github now. And should be available on Chrome Web Store in one week.

**Comment by aminjabari** [comment]
Hi Vinc96
It's interesting. you just added the feature in less than 2 days.
I just tested the new version of the extension.
Beside the Remove Feature, also the Adding feature is handy and useful.

I just want to suggest some other tiny improvements. Although, it seems that you have made them deliberately and intentionally.

1- Any time I remove or change the delimiter, all of the words in the highlight field disappear. 

2- In every page, highlighting doesn't start unless you hit the extension icon. Is it possible to run the extension by default? instead, adding an On/Off switch allow users to deactivate the extension any time they want.

3- When adding a large number of words (for example 1000 words), it is hard to deal with highlight field. It has a short height. Maybe increasing its height may improve the usability of extension.too.

4- The last can be Considered as a new feature.
We can read PDF files in chrome. But this extension does not work in pdf contents. 
In the past, I used to convert the pdf to Webpage format in order to use this extension. I can assure you that this feature is not available in any pdf reader software. There are some but they just cover the minority of your extension features and only the experts have the knowledge to use them.

I was just wondering myself that could it be solved by this extension?

Thanks Again for your efforts, especially for the fast response.
Good Luck

**Comment by vinc96** [comment]
Hi aminjabari,
I will consider a better implementation to resolve issue 1,2,3 you mentioned.
Issues 4 sounds like a very useful feature. I will further investigate it and implement it if feasible.
These might take weeks to finish too.

Thanks for your detailed feedback and fast response.
Good Luck

**Comment by aminjabari** [comment]
I can't stay to see the outcome.
Good Luck
