### ISSUE TITLE
[Feature Request] Customizable colors

### ISSUE THREAD

**Issue by Natedude** [yiminzme/Multi-Highlight#32]
I would love it if I could customize the color. I imagine I could click on the words with color borders at the bottom of the extension pop-up and then a little color selector would pop-up and I could choose a color for that word / line of words. It would also be nice if there was a list either of recently used colors and/or a list of all the currently in-use colors.

Awesome extension! Thanks!

**Comment by bedge** [comment]
Agree 100%
If I could have a say in this, would be nice to have a json/yaml import/export, so one could share string/tegex -> color settings among other apps that offer similar functionality.
As an example, I use iterm2, which has a profile import/export which includes trigger string/regexes to alter color.
With the import/export, one could write a remapper to use the same color definitions in multiple places.

**Comment by yiminzme** [comment]
No plan on this yet.
