### ISSUE TITLE
Options won't save

### ISSUE THREAD

**Issue by theweeeknd** [yiminzme/Multi-Highlight#37]
just always reset when i open this setting page next time

![image_695](https://user-images.githubusercontent.com/84619641/160103830-3e44c93d-816b-4c27-b0c9-ff2c8cfbbe10.png)

**Comment by psuedoward** [comment]
getting the same. Always resets and no indication that any setting are being applied or saved.

Is this supposed to modify a file or something? Is there any way for me(or anyone) to modify a config file or line of code to change these so that it's persistent?
