### ISSUE TITLE
Feature Request: Keyboard shortcut to open window to add/edit words

### ISSUE THREAD

**Issue by devvik** [yiminzme/Multi-Highlight#39]
Feature Request: Keyboard shortcut to open window to add/edit words
Even better, if the shortcut itself can be defined by the user (in addition to having some default shortcut).

**Comment by TroyDanielFZ** [comment]
Hi, @devvik , it is already supported by go to `Extension Manager→Keyboard Shortcuts→Multi Highlight→Activate the extension`. I defined this as `Ctrl+Shfit+F` and use very often.

**Comment by devvik** [comment]
Thanks @TroyDanielFZ for you response. Does this work for (Chrome on) Mac OS? I am using this extension on Chrome installed on a MacBook and this is not working.

**Comment by yiminzme** [comment]
Hi @devvik, in chrome, you can visit chrome://extensions/shortcuts to check and change the shortcut.
