### ISSUE TITLE
It doesn't show highlighted key word immediately 

### ISSUE THREAD

**Issue by 775405984** [yiminzme/Multi-Highlight#41]
https://navi.cnki.net/knavi/journals/ZGSF/detail
But Multi-highlight 1.21 does.
[Multi-highlight 1.21.zip](https://github.com/yiminzme/Multi-Highlight/files/8807311/Multi-highlight.1.21.zip)

**Comment by yiminzme** [comment]
Hi @775405984, the new behavior is to ensure that web content is fully loaded before highlighting. Otherwise, some highlights might be missed on some websites that don't load all content at once. 
You may refer to https://github.com/yiminzme/Multi-Highlight/issues/26 which should be the cause of behavior change.

**Comment by 775405984** [comment]
> Hi @775405984, the new behavior is to ensure that web content is fully loaded before highlighting. Otherwise, some highlights might be missed on some websites that don't load all content at once. You may refer to #26 which should be the cause of behavior change.

But even if web content is fully loaded, your extension still fails to show highlighted key word on this website.
https://navi.cnki.net/knavi/journals/ZGSF/detail
Thanks for replying by the way.

**Comment by yiminzme** [comment]
Indeed, the later versions don't work with iframe. See if anyone can fix it soon.

**Comment by 775405984** [comment]
>  Thanks for providing the older version
Multi-highlight 1.21.zip is another extension:
![image](https://user-images.githubusercontent.com/7196377/172397992-43e33299-79b7-4337-a960-6c0d160ffc84.png)

**Comment by yiminzme** [comment]
Yeah, it is iterated to a newer version, you can't find the 1.21 on google web store anymore. We have to fix the iframe issue in the newer version.
