### ISSUE TITLE
Can you add a shortcut key: enable/disable highlight？

### ISSUE THREAD

**Issue by MILKMILKKING** [yiminzme/Multi-Highlight#42]
Thank you for designing the plugin, it's great! But I put in too many keywords, which caused the opening of other pages to slow down. My idea is to 1. save the keywords entered; 2. turn off highlighting by default when opening web pages; 3. press the shortcut key to turn on highlighting when I need to use it.

**Comment by yiminzme** [comment]
Once auto-highlighting is off, you can manually call the highlighting by clicking the extension icon (or using shortcut ctrl+shift+f).
