### ISSUE TITLE
Highlighting sometimes affects text size/weight as well

### ISSUE THREAD

**Issue by bedge** [yiminzme/Multi-Highlight#43]
Disabled:
<img width="512" alt="ss-2022-21-17_08 21 07" src="https://user-images.githubusercontent.com/499317/174328700-6a45dc8d-1ba3-4439-bb8e-a8741b1ee7a1.png">

Enabled:
<img width="513" alt="ss-2022-20-17_08 20 57" src="https://user-images.githubusercontent.com/499317/174328719-e208ef64-43a6-4cf7-952f-c2f11eeef6f8.png">

Note the 'dev' text, the size should not change.

This is on a Jira page if that helps

**Comment by yiminzme** [comment]
Similar to #44

**Comment by bedge** [comment]
https://chrome.google.com/webstore/detail/multi-highlight/ghinpogonpmlphfkmnjfapdaoaainejn
2.9.0
<img width="564" alt="Screen Shot 2022-06-27 at 14 22 38" src="https://user-images.githubusercontent.com/499317/176037821-f221f42e-fcc1-4ea1-a705-0a991ede15d3.png">
