### ISSUE TITLE
Customizable highlighting colors

### ISSUE THREAD

**Issue by 775405984** [yiminzme/Multi-Highlight#46]
Is there any way you can implement an option to change the color of each word?

And also, Chinese language support, PLEASE!
If you need any help of localization (language, not tech stuff), ask me any time.

thx

**Comment by yiminzme** [comment]
Hi, good idea for the first point.

As for localization, it would be better to do it when the extension's wording is nearly finalized. Based on our progress, it might be months later.

**Comment by yiminzme** [comment]
Similar to #32
