### ISSUE TITLE
插件很好用

### ISSUE THREAD

**Issue by lim8639** [yiminzme/Multi-Highlight#48]
现在也支持动态加载的dom高亮了，请问有打算升级到manifest V3吗

**Comment by yiminzme** [comment]
感觉这个优先度比较低。半年内应该不会做。你熟悉v3的话，非常欢迎你做个adaptation 👍

**Comment by yiminzme** [comment]
Here is a kind-of-official script that helps to convert from v2 to v3 [link](https://developer.chrome.com/blog/extension-manifest-converter/). Seems like you know python, so may have a try.
I have tried. It does most of the conversion (I think), but still needs to manually update some parts, e.g. background, executeScript part.
