### ISSUE TITLE
React.js/Inifinite Scroll/Scroll to load more does not automatically hightlight new matches

### ISSUE THREAD

**Issue by JonesMikael** [yiminzme/Multi-Highlight#49]
Love this extension since it replaces one I have in Chrome. I use it for search for a textscring in various portals. For example I want to highlight a serial number that it available in a huge list in a portal. Problem is that the site I'm searching on has moved from pre-loading the whole list of serial numbers to using "scroll down to load" instead of pre-loading the whole page. I think it's called "React.js" or "Infinite scroll".

This means that if I enter the serialnumber to highligt I have to press "Reset highlighting" for every scroll I do and with thousands of rows that means I have to reset highlighting many times. The other extension I used seems to reset/reload/re-highligt for every scroll I do automatically. Maybe add this as an option since I guess it will take some performance.

**Comment by yiminzme** [comment]
Hi, could you provide a link to the webpage you mentioned?

**Comment by JonesMikael** [comment]
It requires a login but let me see if I can find some public example.

**Comment by yiminzme** [comment]
In case you can't find a similar public example. Is your Multi Highlight version 2.9.0? We just added a feature relating to this in version 2.9.0.
