### ISSUE TITLE
[Suggestion] Have a different delimiter to change color or use a color for each line instead of changing for each word

### ISSUE THREAD

**Issue by FuurioBR** [yiminzme/Multi-Highlight#5]
Could please add this function? This would help so much!
Also, if the word appear more than one time, would be nice to have a option to not highlight, totally optional, this can help in some situations...
I really need this :(

**Comment by FuurioBR** [comment]
Also, I noticed that it only highlight words in a new tab when the extension icon is clicked, would be nice to do it automatically

**Comment by vinc96** [comment]
Thanks for your suggestion. I will implement them soon.

**Comment by yiminzme** [comment]
> Have a different delimiter to change color or use a color for each line instead of changing for each word

> I noticed that it only highlight words in a new tab when the extension icon is clicked, would be nice to do it automatically

The extension now can use a color for each line, and can automatically highlight in new tab. Thanks for your suggestion.

> if the word appear more than one time, would be nice to have a option to not highlight, totally optional, this can help in some situations...

Most browsers have this feature by default. You can quickly access it with shortcut ctrl+f or command+f.
