### ISSUE TITLE
[Bug] Incompatible with Chrome built-in translator

### ISSUE THREAD

**Issue by reclusem** [yiminzme/Multi-Highlight#50]
**Extension Version:** `2.9.0`

**Chrome Version:** `103.0.5060.53`

**Problem Description:** loop to generate duplicate content

**Problem Screenshot:**

![20220627223213](https://user-images.githubusercontent.com/15794778/175971289-d11ad223-92df-4cf4-9a8e-6273872b1dd1.jpg)
![20220627230148](https://user-images.githubusercontent.com/15794778/175972084-9c7eb7f8-3fa5-45e7-8736-9bd35016ed41.jpg)

**Comment by yiminzme** [comment]
With the upcoming version, we will have an auto-rehighlight feature replacing the "auto-highlight". You can avoid this problem by disabling the auto-rehighlight when using the Chrome's built-in translator.
