### ISSUE TITLE
[Bug] Highlighting makes target word invisible in Google slides

### ISSUE THREAD

**Issue by bedge** [yiminzme/Multi-Highlight#51]
**Describe the bug**
Editing a goole slides shows odd text visibility behavior

**To Reproduce**
1. Create google slides
2. click on text to edit
3. type "postgresql"
4. The letters after "post" are not shown
5. If I hit "enter" I see "poresql" rather than "postgresql"

**Expected behavior**
No impact on the text visibility

**Additional context**
Problem goes away when I disable this extension
Note, it has to be disabled in chrome, not just turned off in the extension's own panel

I believe it may be interacting with google's autocomplete/suggestions, but it's more than that as even after hitting "enter", the last half of the word is corrupted.

Observe as you type, letters after the initial "post" are not shown, even though the cursor advances.

**Comment by yiminzme** [comment]
Might relate to #44, as both seems to break css.

**Comment by yiminzme** [comment]
Ok, have re-checked this issue. Google Slides app seems to be highly engineered, it is too complicated for me to make multi-highlight compatible with it. So now multi-highlight won't work with Google Slides. 
Pull requests are welcome.
