### ISSUE TITLE
[Bug] Duplicated text after turn on Multi-Highlight

### ISSUE THREAD

**Issue by 775405984** [yiminzme/Multi-Highlight#52]
**Describe the bug**
After turn on Multi-Highlight and enter a keyword, the sentence got messed up.

**To Reproduce**
1. Go to the website http://zhnfmdxzz.yiigle.com/CN311282202111/index.jhtml?tplReset=qikan#co0
2. Enter keyword 指南 in Multi-Highlight.
3. Scroll down to expect this:
![image](https://user-images.githubusercontent.com/7196377/178018343-3f010bb3-7e5e-4522-9aab-c9a1de5f0fe9.png)

4. But instead you see error like this:
![image](https://user-images.githubusercontent.com/7196377/178018538-288dd389-1dd8-4824-82b4-f35f35550b9f.png)

**Comment by 775405984** [comment]
If you can't reproduce, refresh and see.

**Comment by 775405984** [comment]
@yiminzme @TroyDanielFZ

**Comment by TroyDanielFZ** [comment]
@775405984 I can't reproduce it. Can you turn all the extensions except Multi-Highlight off and refresh to see whether it happen again?

**Comment by yiminzme** [comment]
@775405984 I can't reproduce it too, neither Chrome nor Edge browser. 
But it seems to be similar to #50, which generates duplicate words unintentionally.

**Comment by yiminzme** [comment]
@775405984 Is the problem still persist on your side?
With the upcoming version, we will have an auto-rehighlight feature replacing the "auto-highlight". You can avoid this problem by disabling the auto-rehighlight when using the Chrome's built-in translator.
