### ISSUE TITLE
[Bug] The extension layout size is abnormal

### ISSUE THREAD

**Issue by uctdsb** [yiminzme/Multi-Highlight#58]
**Describe the bug**
the extension layout size is abnormal.
![image](https://user-images.githubusercontent.com/113759182/190845563-9a96d1e9-db61-4e6b-94b5-60653d3ec6bf.png)
even if I adjust the Option 

Reset the chrome could fix it sometimes.
I don't know the exact reproduce steps, but it happens often.

**Comment by yiminzme** [comment]
It is because the code is broken somewhere (js fail to work). Hopefully, with the next update, all critical bugs are removed so this won't happen.
