### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by KSimonnet** [yiminzme/Multi-Highlight#6]
A keyword can also be a string comprised of multiple substrings. Should the string be enclosed between a separator (e.g. "The quick fox"), is it possible to have it considered as one regular expression?
Apparently the feature _"Highlight any strings (not just full word)"_ exists, however I haven't been able to make it work. Could you please detail how to use it?

Same for _"Add customizable delimiter"_

Thanks

PS: I got it to work with https://chrome.google.com/webstore/detail/multi-highlight/ghinpogonpmlphfkmnjfapdaoaainejn/

**Comment by yiminzme** [comment]
Hi KSimonnet,

This code for https://chrome.google.com/webstore/detail/multi-highlight/ghinpogonpmlphfkmnjfapdaoaainejn/ should be the same as the one here at github. 
Both are maintained by me.

Thanks
