### ISSUE TITLE
Keywords not exist when working in Multiple Tabs 

### ISSUE THREAD

**Issue by Ekitji** [yiminzme/Multi-Highlight#62]
Adding keyword does not follow to already opened tabs in chrome. Only tabs opened after the Word is added shows up in next tab. Is it possible to temporary store keywords localy which each tabs read/writes/edits? Could Local Storage work?

My problem is that i may open 4 tabs and highlight words in first tab to later check if words exist in the other tabs..and its even common that i add keywords in second tab that i need highlight for my 3rd tab and it goes on like that :)

**Comment by yiminzme** [comment]
> Adding keyword does not follow to already opened tabs in chrome. Only tabs opened after the Word is added shows up in next tab.
Refresh opened tabs to load the latest word list. Btw, remember to check the "Save words" feature.
