### ISSUE TITLE
[Feature Request] In editable text boxes possible?

### ISSUE THREAD

**Issue by Frigazord** [yiminzme/Multi-Highlight#63]
I've been looking for a highlight extension for my job. I work for a company that approves videos, and when we look at the video the text is in editable boxes like the one im writing this request in here. 
There are a lot of words that are not allowed on the website but non of the extensions i've tried highlight words in these text boxes. Is it possible to do so?

<3 much love

**Comment by yiminzme** [comment]
We highlight text using CSS. Text in textbox don't have CSS properties, so they are not highlightable.
