### ISSUE TITLE
【bug】The Edge browser cannot be highlighted in real time

### ISSUE THREAD

**Issue by suchascome** [yiminzme/Multi-Highlight#65]
When I use this plugin on the Edge browser, it cannot be highlighted in real time, and I need to manually refresh the plugin every time the page content changes

**Comment by suchascome** [comment]
Ajax technology is so ubiquitous that it's important to be able to highlight it in real time

**Comment by yiminzme** [comment]
Is the "real-time highlight" checkbox checked?

**Comment by suchascome** [comment]
> Is the "real-time highlight" checkbox checked?

![image](https://user-images.githubusercontent.com/39409443/222952906-ab643f57-5ae7-4eba-92d6-711230f073a3.png)
The Edge browser store has fewer real-time search options than the Chrome Store

**Comment by yiminzme** [comment]
Oh, get the chrome store version. Edge store version is currently outdated.

**Comment by suchascome** [comment]
> Oh, get the chrome store version. Edge store version is currently outdated.

Ok, I'll try the Chrome Store version, thank you very much for your help.
