### ISSUE TITLE
Question about possible future implementations

### ISSUE THREAD

**Issue by rvzzz** [yiminzme/Multi-Highlight#7]
Hi! Hope everything is okay with you!

Thank you for the extension! Just wondering if it could be possible to implement the search feature with all these options with asterisks (it could be another distinctive character):

- or           (` just the word "or"`)

- \*or\*      (`words containing the substring "or" like in the word "storm"`)

- or\*        (`words starting with the substring "or" like in the word "origami"`)

- \*or        (`words ending with the substring "or" like in the word "honor"`)

And also...in the future would be cool to use regular expressions as an "advance mode"

Bye, have a good day.

**Comment by rvzzz** [comment]
I will try to implement it, thanks.

**Comment by yiminzme** [comment]
Thank would be nice! Hope you can make it :-)
