### ISSUE TITLE
[Bug] Escape Commas for Searches for Dollar Amounts

### ISSUE THREAD

**Issue by QGtKMlLz** [yiminzme/Multi-Highlight#72]
I was trying to search/Highlight  "10,000" but it always treats it as "10" and "000"

I have tried backslash, backtick, quotations, and single-quotations to escape the comma. 

Is there a way an escape method can be added?

**Comment by KSR-Yasuda** [comment]
Why don't you change the Word Separator setting?

![MultiHighlight_20240325_085833](https://github.com/yiminzme/Multi-Highlight/assets/31273423/96b8c73f-c9db-4baf-ac1c-0950a0b5f553)

**Comment by QGtKMlLz** [comment]
Ooh jeez..;  I’m very sorry I took up your attention.
